# Generated by Django 5.2 on 2025-05-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Appartement', 'Appartement'), ('Maison', 'Maison'), ('Terrain', 'Terrain')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=7)),
                ('adresse', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('statut', models.CharField(choices=[('Libre', 'Libre'), ('Loué', 'Loué')], default='Libre', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biens.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biens.tenant')),
            ],
        ),
    ]
