# Generated by Django 5.2 on 2025-05-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_type_remove_lease_property_remove_lease_tenant_bien_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeBail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en attente', max_length=20)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biens.bien')),
                ('locataire', models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
