# Generated by Django 5.2 on 2025-05-17 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0003_demandebail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bail',
            name='garantie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
