# Generated by Django 5.2 on 2025-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0004_bail_date_creation_bail_garantie'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='adresse_locataire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bail',
            name='adresse_proprietaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bail',
            name='locataire_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bail',
            name='proprietaire_valide',
            field=models.BooleanField(default=False),
        ),
    ]
