# Generated by Django 5.2 on 2025-05-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0005_bail_adresse_locataire_bail_adresse_proprietaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bail',
            old_name='locataire_valide',
            new_name='est_valide_locataire',
        ),
        migrations.RenameField(
            model_name='bail',
            old_name='proprietaire_valide',
            new_name='est_valide_proprio',
        ),
    ]
