# Generated by Django 5.2 on 2025-05-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0006_rename_locataire_valide_bail_est_valide_locataire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mois_paye', models.CharField(max_length=20)),
                ('est_valide', models.BooleanField(default=False)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='biens.bail')),
            ],
        ),
    ]
