# Generated by Django 5.2 on 2025-05-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0009_alter_paiement_locataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
